# Generated by Django 4.2 on 2023-09-26 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("tool_tip", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="images/no-image@2x.png",
                        null=True,
                        upload_to="images/tournament",
                    ),
                ),
                (
                    "score_prediction_model",
                    models.FileField(blank=True, null=True, upload_to="models/score"),
                ),
                (
                    "first_innings_win_prediction_model",
                    models.FileField(
                        blank=True, null=True, upload_to="models/first_innings_win"
                    ),
                ),
                (
                    "second_innings_win_prediction_model",
                    models.FileField(
                        blank=True, null=True, upload_to="models/second_innings_win"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=5000, null=True),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VenueName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_venue",
                        to="tournament.tournament",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="TeamName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team", models.CharField(blank=True, max_length=100, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_team",
                        to="tournament.tournament",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
