# Generated by Django 4.2 on 2023-09-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(blank=True, max_length=500, null=True)),
                ("answer", models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
